[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	coryjfowler/mcp_can@^1.5.1
	h2zero/NimBLE-Arduino@^1.4.1
board_build.partitions = min_spiffs.csv
;upload_protocol = espota
;upload_port = 10.180.3.211